### ISSUE TITLE
CSS change: Top LHS title needs to be sharply aligned to the left

### ISSUE THREAD

**Issue by shashank-srikant** [shashank-srikant/sevasetu-mothercare#7]
Currently, a lot of whitespace exists. This is beause i just reused the CSS class meant for the Logout button. Some minor CSS mods need to be made to remove that extra whitespace

**Comment by shashank-srikant** [comment]
Also, is there a possibility to put in Seva Setu's logo in the header banner? Colors don't match.
The logo is on - sevasetu.org

**Comment by haptork** [comment]
Just want to confirm that it is regarding the header defined in [admin_header.blade.php](https://github.com/shashank-srikant/sevasetu-mothercare/blob/7ba0cc2f10705a1290ac5ba47da077c75742efdd/resources/views/template/admin_header.blade.php).

How about trying with black and white colours instead of the original colours?

**Comment by shashank-srikant** [comment]
Yes, referring to the file pointed in the comment.
I'm okay with the any colorset as long as it can accommodate the logo.
If that;s too time consuming to tinker around with, can simply align the
current text correctly and return to this later.
